package bing;

import bing.log.JTextAreaLogAppender;
import bing.thread.TaskThread;
import bing.util.ExceptionUtils;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.apache.commons.lang3.StringUtils;
import org.jvnet.substance.skin.SubstanceOfficeBlue2007LookAndFeel;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * 订单闭环工具
 *
 * @author IceWee
 */
public class AppUI extends JFrame {

    private static final Logger LOGGER = LoggerFactory.getLogger(AppUI.class);

    private static final ImageIcon APP_ICON;

    private static JTextAreaLogAppender logThread; // 日志线程

    static {
        URL url = AppUI.class.getResource(Constants.ICON_APP_PATH);
        APP_ICON = new ImageIcon(url);
    }

    /**
     * Creates new form AppUI
     */
    public AppUI() {
        // 初始化UI
        initComponents();
        // 初始化log4j日志输出控制台
        initLogConsole();
        // 初始化版权
        initCopyright();
        LOGGER.info("感谢使用 订单闭环工具");
    }

    /**
     * 初始化日志控制台
     */
    private void initLogConsole() {
        try {
            // 说明：gui对应log4j.properties中的配置，是appender的名称
            if (logThread != null) {
                logThread.setRun(false);
                logThread = null;
            }
            logThread = new JTextAreaLogAppender("gui", this.console, this.logScrollPane);
            logThread.start();
        } catch (IOException e) {
            String error = ExceptionUtils.createExceptionString(e);
            LOGGER.error("初始化日志控制台时出现了异常...\n{}", error);
        }
    }

    /**
     * 初始化版权
     */
    private void initCopyright() {
        Calendar calendar = Calendar.getInstance();
        int year = calendar.get(Calendar.YEAR);
        this.copyrightLabel.setText("® " + year + " 长公子冰");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        configPanel = new javax.swing.JPanel();
        exeButton = new javax.swing.JButton();
        orderPathLabel = new javax.swing.JLabel();
        sqlPathLabel = new javax.swing.JLabel();
        orderPathTextField = new javax.swing.JTextField();
        sqlPathTextField = new javax.swing.JTextField();
        choseOrderPathButton = new javax.swing.JButton();
        choseSqlPathButton = new javax.swing.JButton();
        tipsLabel = new javax.swing.JLabel();
        logPanel = new javax.swing.JPanel();
        logScrollPane = new javax.swing.JScrollPane();
        console = new bing.ui.JTextAreaExt();
        copyrightLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("订单闭环工具");

        configPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "配置面板", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑", 0, 18))); // NOI18N
        configPanel.setFont(new java.awt.Font("宋体", 3, 18)); // NOI18N

        exeButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        exeButton.setText("生成SQL");
        exeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exeButtonActionPerformed(evt);
            }
        });

        orderPathLabel.setFont(new java.awt.Font("微软雅黑", 1, 15)); // NOI18N
        orderPathLabel.setText("订单文件目录：");

        sqlPathLabel.setFont(new java.awt.Font("微软雅黑", 1, 15)); // NOI18N
        sqlPathLabel.setText("SQL文件目录：");

        orderPathTextField.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        orderPathTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderPathTextFieldActionPerformed(evt);
            }
        });

        sqlPathTextField.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N

        choseOrderPathButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        choseOrderPathButton.setText("浏  览..");
        choseOrderPathButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        choseOrderPathButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choseOrderPathButtonActionPerformed(evt);
            }
        });

        choseSqlPathButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        choseSqlPathButton.setText("浏  览..");
        choseSqlPathButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        choseSqlPathButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choseSqlPathButtonActionPerformed(evt);
            }
        });

        tipsLabel.setFont(new java.awt.Font("微软雅黑", 2, 15)); // NOI18N
        tipsLabel.setText("提示：允许选择单个文本文件或者文件夹，每个文件会生成一个同名SQL文件");

        javax.swing.GroupLayout configPanelLayout = new javax.swing.GroupLayout(configPanel);
        configPanel.setLayout(configPanelLayout);
        configPanelLayout.setHorizontalGroup(
            configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(configPanelLayout.createSequentialGroup()
                        .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(configPanelLayout.createSequentialGroup()
                                .addComponent(sqlPathLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sqlPathTextField))
                            .addGroup(configPanelLayout.createSequentialGroup()
                                .addComponent(orderPathLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(orderPathTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))
                    .addGroup(configPanelLayout.createSequentialGroup()
                        .addComponent(tipsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(exeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(choseOrderPathButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(choseSqlPathButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        configPanelLayout.setVerticalGroup(
            configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exeButton)
                    .addComponent(tipsLabel))
                .addGap(18, 18, 18)
                .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderPathLabel)
                    .addComponent(orderPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(choseOrderPathButton))
                .addGap(18, 18, 18)
                .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sqlPathLabel)
                    .addComponent(sqlPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(choseSqlPathButton))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        logPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "运行日志", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑", 0, 18))); // NOI18N

        console.setColumns(20);
        console.setRows(5);
        logScrollPane.setViewportView(console);

        javax.swing.GroupLayout logPanelLayout = new javax.swing.GroupLayout(logPanel);
        logPanel.setLayout(logPanelLayout);
        logPanelLayout.setHorizontalGroup(
            logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logScrollPane)
        );
        logPanelLayout.setVerticalGroup(
            logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
        );

        copyrightLabel.setFont(new java.awt.Font("微软雅黑", 1, 15)); // NOI18N
        copyrightLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        copyrightLabel.setText("© 2017 长公子冰");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(configPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(copyrightLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(configPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(copyrightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void orderPathTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderPathTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderPathTextFieldActionPerformed

    /**
     * 选择订单文件目录
     *
     * @param evt
     */
    private void choseOrderPathButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choseOrderPathButtonActionPerformed
        JFileChooser chooser = new JFileChooser(orderPathTextField.getText());
        chooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        chooser.showOpenDialog(this);
        File orderPath = chooser.getSelectedFile();
        if (orderPath != null) {
            orderPathTextField.setText(orderPath.getAbsolutePath());
        }
    }//GEN-LAST:event_choseOrderPathButtonActionPerformed

    /**
     * 选择SQL文件生成目录
     *
     * @param evt
     */
    private void choseSqlPathButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choseSqlPathButtonActionPerformed
        JFileChooser chooser = new JFileChooser(orderPathTextField.getText());
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.showOpenDialog(this);
        File sqlPath = chooser.getSelectedFile();
        if (sqlPath != null) {
            sqlPathTextField.setText(sqlPath.getAbsolutePath());
        }
    }//GEN-LAST:event_choseSqlPathButtonActionPerformed

    /**
     * 运行
     *
     * @param evt
     */
    private void exeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exeButtonActionPerformed
        if (valid()) {
            TaskThread thread = new TaskThread(this, orderPathTextField.getText(), sqlPathTextField.getText());
            new Thread(thread).start();
            buttonsDisabled();
        }
    }//GEN-LAST:event_exeButtonActionPerformed

    /**
     * 条件检查
     *
     * @return
     */
    private boolean valid() {
        String orderPath = this.orderPathTextField.getText();
        if (StringUtils.isBlank(orderPath)) {
            JOptionPane.showMessageDialog(this, "请选择订单文件路径或目录！", "提示信息", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        String sqlPath = this.sqlPathTextField.getText();
        if (StringUtils.isBlank(sqlPath)) {
            JOptionPane.showMessageDialog(this, "请选择SQL生成目录！", "提示信息", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        if (StringUtils.equalsIgnoreCase(orderPath, sqlPath)) {
            JOptionPane.showMessageDialog(this, "SQL生成目录不能与订单文件目录相同！", "警告信息", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }

    /**
     * 按钮可用
     */
    public void buttonsEnabled() {
        this.exeButton.setEnabled(true);
        this.choseOrderPathButton.setEnabled(true);
        this.choseSqlPathButton.setEnabled(true);
    }

    /**
     * 按钮不可用
     */
    private void buttonsDisabled() {
        this.exeButton.setEnabled(false);
        this.choseOrderPathButton.setEnabled(false);
        this.choseSqlPathButton.setEnabled(false);
    }

    /**
     * 执行完成
     */
    public void completed() {
        LOGGER.info("订单闭环更新SQL生成完毕.....");
        buttonsEnabled();
        try {
            String sqlPath = this.sqlPathTextField.getText();
            java.awt.Desktop.getDesktop().open(new File(sqlPath));
        } catch (IOException ex) {
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // 设置主题风格
        setlookAndFeel();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            AppUI app = new AppUI();
            app.setIconImage(APP_ICON.getImage());
            int w = (int) (Toolkit.getDefaultToolkit().getScreenSize().getWidth() - app.getWidth()) / 2;
            int h = (int) (Toolkit.getDefaultToolkit().getScreenSize().getHeight() - app.getHeight()) / 2;
            app.setLocation(w, h);
            app.setVisible(true);
        });
    }

    /**
     * 设置主题风格
     */
    static void setlookAndFeel() {
        try {
            UIManager.setLookAndFeel(new SubstanceOfficeBlue2007LookAndFeel());
        } catch (UnsupportedLookAndFeelException e) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton choseOrderPathButton;
    private javax.swing.JButton choseSqlPathButton;
    private javax.swing.JPanel configPanel;
    private bing.ui.JTextAreaExt console;
    private javax.swing.JLabel copyrightLabel;
    private javax.swing.JButton exeButton;
    private javax.swing.JPanel logPanel;
    private javax.swing.JScrollPane logScrollPane;
    private javax.swing.JLabel orderPathLabel;
    private javax.swing.JTextField orderPathTextField;
    private javax.swing.JLabel sqlPathLabel;
    private javax.swing.JTextField sqlPathTextField;
    private javax.swing.JLabel tipsLabel;
    // End of variables declaration//GEN-END:variables
}
